plugins {
    id 'java'
    id 'io.qameta.allure-adapter' version '3.0.2'
    id 'io.qameta.allure-report' version '3.0.2'
}

group = 'com.example'
version = '1.1.0'

repositories {
    mavenCentral()
}

ext {
    playwrightVersion = '1.58.0'
    junitVersion = '6.0.3'
    allureVersion = '2.30.0'
    ownerVersion = '1.0.12'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation platform("io.qameta.allure:allure-bom:${allureVersion}")

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "com.microsoft.playwright:playwright:${playwrightVersion}"
    testImplementation 'io.qameta.allure:allure-junit5'
    testImplementation "org.aeonbits.owner:owner:${ownerVersion}"

    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.17'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()

    environment 'PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD', '1'
    systemProperty 'file.encoding', 'UTF-8'

    testLogging {
        events 'passed', 'skipped', 'failed'
        exceptionFormat 'full'
        showExceptions true
        showCauses true
        showStackTraces true
    }
}

allure {
    adapter {
        autoconfigure.set(true)
        aspectjWeaver.set(false)

        frameworks {
            junit5 {
                enabled.set(true)
            }
        }
    }

    report {
        version.set(allureVersion)
    }
}

tasks.register('installBrowsers', JavaExec) {
    group = 'playwright'
    description = 'Installs Playwright browser binaries based on selected browser parameter.'

    classpath = sourceSets.test.runtimeClasspath
    mainClass.set('com.microsoft.playwright.CLI')

    def browser = System.getProperty('visual.browser', 'chromium')

    args 'install', browser
}